version: "4.27"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: simba
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: WebDevGo
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula

    ports:
      - 3333:8080
